### ISSUE TITLE
Communications about this repo?

### ISSUE THREAD

**Issue by TonyGravagno** [konradmi/zod-hook-form#1]
I've been working on projects with the same tooling and am about to start code that's similar to zod-hook-form, but a little different. So I'm taking a look at this now.
Would you mind creating a Discussion area for this repo so we can exchange notes? Or a GitterIM for it? Or Discord, Slack, _anything_ ? 😸 I also have your email from the code, if you prefer that.
If I do anything with this, I'd like to contribute - if you're interested - or if I do get into it I can fork and you can look there.
However you'd like to collaborate.... Thanks.

**Comment by konradmi** [comment]
Hey! thanks a lot for the message :) I'd love to discuss some ideas. Feel free to send me an email or post in Discussions. Also, if you prefer to fork the repo and contribute, I'd be very happy to check it out. Cheers!
